theme: jekyll-theme-cayman
title: "Ramses Alexander Coraspe Valdez: Building Dashboard with D3.js and ASP.NET MVC "
description: "Building Responsive DashBoard with D3.js and ASP.NET MVC from scratch (SQL SERVER - SSIS - API REST)"
